version: '3'

services:
  demoapp:
    build: .
    expose:
      - 7272
    networks:
      - selenium-grid

  hub:
    image: selenium/hub:3.0.1-germanium
    expose:
      - 4444
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox-debug:3.0.1-germanium
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5901:5900
    depends_on:
      - hub
    networks:
      - selenium-grid

  robot:
    build:
      context: .
      dockerfile: Dockerfile.robottests
    command: -v BROWSER:ff --outputdir /out /tests
    volumes:
      - ./robot/tests:/tests:ro
      - ./results/ff:/out:rw
    depends_on:
      - demoapp
      - firefox
    networks:
      - selenium-grid

networks:
  selenium-grid:
